# Generated by Django 4.2 on 2023-04-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/facility_list')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('parts_intro', models.ImageField(upload_to='images/product')),
                ('sample', models.FileField(upload_to='files/product')),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product/press')),
                ('context', models.TextField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('max_power', models.CharField(blank=True, max_length=255, null=True)),
                ('stroke', models.CharField(blank=True, max_length=255, null=True)),
                ('stroke_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('hydraulic_press', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product_image', models.ImageField(upload_to='images/product/')),
                ('product_features_image', models.ImageField(upload_to='images/product/')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_need_detail', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_image', models.ImageField(upload_to='images/product')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
