# Generated by Django 4.2 on 2023-04-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productgoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgoal',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
