# Generated by Django 4.2 on 2023-04-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_is_press_product_is_need_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('parts_intro', models.ImageField(upload_to='images/product')),
                ('sample', models.FileField(upload_to='files/product')),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
