# Generated by Django 4.2 on 2023-04-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_parts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/facility_list')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
