# Generated by Django 4.2 on 2023-04-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_press'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
