# Generated by Django 4.2 on 2023-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_press_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='press',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='press',
            name='max_power',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='press',
            name='max_stroke_speed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='press',
            name='quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='press',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
