# Generated by Django 4.2 on 2023-04-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('context', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='files/notice/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/notice/')),
                ('division', models.CharField(choices=[('option1', '뉴스'), ('option2', '자료실'), ('option0', '공지사항')], max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
