# Generated by Django 4.2 on 2023-04-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='file',
            field=models.FileField(null=True, upload_to='files/notice/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(null=True, upload_to='images/notice/'),
        ),
    ]
