# Generated by Django 4.2 on 2023-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_title', models.CharField(default='업체개요', max_length=255)),
                ('date_company_founded', models.CharField(max_length=255)),
                ('date_corporation_founded', models.CharField(max_length=255)),
                ('CEO', models.CharField(max_length=255)),
                ('main_item', models.CharField(max_length=255)),
                ('num_employee', models.CharField(max_length=255)),
                ('head_office', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('timeline_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.TextField(default='인사말 예시')),
                ('intro_title', models.CharField(default='소개', max_length=255)),
                ('intro_context', models.TextField(default='소개 내용')),
                ('mainvalues_title', models.CharField(default='핵심가치', max_length=255)),
                ('mainvalues_context', models.TextField(default='핵심가치 내용')),
            ],
        ),
        migrations.CreateModel(
            name='MainBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.TextField(default='주요업무 인트로')),
                ('title', models.CharField(default='제목', max_length=255)),
                ('business_list', models.TextField(default=' 쉼표 로 각 업무 구분,쉼표 로 각 업무 구분,쉼표 로 각 업무 구분')),
                ('share_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
