# Generated by Django 4.2 on 2023-04-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='intro_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='mainvalues_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
