# Generated by Django 4.2 on 2023-04-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_introduction_intro_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='introduction',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainbusiness',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationchart',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
