# Generated by Django 4.2 on 2023-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_history_created_at_introduction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='timeline_img',
            field=models.ImageField(upload_to='images/history/'),
        ),
        migrations.AlterField(
            model_name='mainbusiness',
            name='share_image',
            field=models.ImageField(upload_to='images/mainbusiness/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='map_image',
            field=models.ImageField(upload_to='images/map/'),
        ),
        migrations.AlterField(
            model_name='organizationchart',
            name='chart_image',
            field=models.ImageField(upload_to='images/organizationchart/'),
        ),
    ]
