# Generated by Django 4.2 on 2023-04-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_history_timeline_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='fax_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
