# Generated by Django 4.2 on 2023-04-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_map_fax_number_map_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='background',
            field=models.ImageField(null=True, upload_to='images/history'),
        ),
    ]
