# Generated by Django 4.2 on 2023-04-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_history_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='background',
            field=models.ImageField(null=True, upload_to='images/introduction/'),
        ),
        migrations.AddField(
            model_name='mainbusiness',
            name='background',
            field=models.ImageField(null=True, upload_to='images/mainbusiness/'),
        ),
        migrations.AddField(
            model_name='map',
            name='background',
            field=models.ImageField(null=True, upload_to='images/map/'),
        ),
        migrations.AddField(
            model_name='organizationchart',
            name='background',
            field=models.ImageField(null=True, upload_to='images/organizationchart/'),
        ),
        migrations.AlterField(
            model_name='history',
            name='background',
            field=models.ImageField(null=True, upload_to='images/history/'),
        ),
    ]
