# Generated by Django 4.2 on 2023-04-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_remove_map_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationchart',
            name='chart_image_m',
            field=models.ImageField(null=True, upload_to='images/organizationchart/'),
        ),
    ]
