# Generated by Django 4.2 on 2023-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_organizationchart_chart_image_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/main/')),
                ('phone_number', models.CharField(max_length=50)),
                ('fax_numver', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('brochure', models.FileField(upload_to='files/main')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_en_1', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_kr_1', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_cn_1', models.CharField(blank=True, max_length=255, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='images/main/')),
                ('comment_en_2', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_kr_2', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_cn_2', models.CharField(blank=True, max_length=255, null=True)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='images/main/')),
                ('comment_en_3', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_kr_3', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_cn_3', models.CharField(blank=True, max_length=255, null=True)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='images/main/')),
            ],
        ),
    ]
