# Generated by Django 4.2 on 2023-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_maininfo_mainslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
