# Generated by Django 4.2 on 2023-04-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_map_map_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maininfo',
            old_name='fax_numver',
            new_name='fax_number',
        ),
    ]
