# Generated by Django 4.2 on 2023-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_rename_fax_numver_maininfo_fax_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininfo',
            name='brochure',
        ),
        migrations.RemoveField(
            model_name='maininfo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='maininfo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='fax_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/maininfo/'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
