# Generated by Django 4.2 on 2023-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_maininfo_brochure_maininfo_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maininfo',
            old_name='location',
            new_name='location_cn',
        ),
        migrations.RenameField(
            model_name='maininfo',
            old_name='name',
            new_name='location_en',
        ),
        migrations.AddField(
            model_name='maininfo',
            name='location_kr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='name_cn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maininfo',
            name='name_kr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
