# Generated by Django 4.2 on 2023-04-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_rename_location_maininfo_location_cn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_image', models.ImageField(upload_to='images/main/')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
