# Generated by Django 4.2 on 2023-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_revenue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainbusiness',
            old_name='share_image',
            new_name='work2_image',
        ),
        migrations.AddField(
            model_name='mainbusiness',
            name='work1_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/mainbusiness/'),
        ),
    ]
