# Generated by Django 4.2 on 2023-04-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_rename_share_image_mainbusiness_work2_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininfo',
            name='location_cn',
        ),
        migrations.RemoveField(
            model_name='maininfo',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='maininfo',
            name='name_cn',
        ),
        migrations.RemoveField(
            model_name='mainslide',
            name='comment_cn_1',
        ),
        migrations.RemoveField(
            model_name='mainslide',
            name='comment_cn_2',
        ),
        migrations.RemoveField(
            model_name='mainslide',
            name='comment_cn_3',
        ),
        migrations.RemoveField(
            model_name='mainslide',
            name='comment_en_1',
        ),
        migrations.RemoveField(
            model_name='mainslide',
            name='comment_en_2',
        ),
        migrations.RemoveField(
            model_name='mainslide',
            name='comment_en_3',
        ),
        migrations.AddField(
            model_name='mainslide',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='image_1_m',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='image_2_m',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='image_3_m',
            field=models.ImageField(blank=True, null=True, upload_to='images/main/'),
        ),
    ]
