# Generated by Django 4.2 on 2023-04-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_remove_maininfo_location_cn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslide',
            name='context_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='context_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainslide',
            name='context_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
